### ISSUE TITLE
Grissom Light Science Vessel doesn't populate Boff slots past CMDR Science/Temporal

### ISSUE THREAD

**Issue by Serious-Table** [STOCD/SETS#43]
Exception generated

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/mnt/sda1/Repos/SETS/main.py", line 222, in <lambda>
    self.backend['tier'].trace_add('write', lambda v,i,m:self.setupBuildFrames())
  File "/mnt/sda1/Repos/SETS/main.py", line 617, in setupBuildFrames
    self.setupBoffFrame(self.backend['shipHtml'])
  File "/mnt/sda1/Repos/SETS/main.py", line 602, in setupBoffFrame
    self.backend['i_'+boffSan][i] = image
KeyError: 'i_Science'
```

**Comment by Serious-Table** [comment]
This if now fixed.
