### ISSUE TITLE
An'quat command battlecruiser boff stations missing

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#53]
An'quat War Command Battlecruiser.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Desktop\python\SETS\main.py", line 412, in <lambda>
    self.backend['tier'].trace_add('write', lambda v,i,m:self.setupSpaceBuildFrames())
  File "D:\Desktop\python\SETS\main.py", line 1110, in setupSpaceBuildFrames
    self.setupSpaceBoffFrame(self.backend['shipHtml'])
  File "D:\Desktop\python\SETS\main.py", line 1040, in setupSpaceBoffFrame
    if boffSan in self.build['boffs'] and self.build['boffs'][boffSan][i] is not None:
IndexError: list index out of range

**Comment by Shinga13** [comment]
Same issue with the Kelvin T'laru intel warbird carrier
