### ISSUE TITLE
Keep template when clearing ships - T5U console

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#77]
Not breaking anything, just throwing the following error: On changing ships away from a T5U to a ship lacking T5U console slot with having "Keep template when clearing ship" setting enabled

```Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Desktop\python\SETS\main.py", line 2114, in shipPickButtonCallback
    self.setupCurrentBuildFrames('space')
  File "D:\Desktop\python\SETS\main.py", line 2980, in setupCurrentBuildFrames
    self.setupSpaceBuildFrames()
  File "D:\Desktop\python\SETS\main.py", line 3652, in setupSpaceBuildFrames
    self.setupShipGearFrame(self.backend['shipHtml'])
  File "D:\Desktop\python\SETS\main.py", line 3167, in setupShipGearFrame
    t5console = ship["t5uconsole"]
KeyError: 't5uconsole'```

**Comment by Shinga13** [comment]
I cannot replicate the issue anymore, so maybe I fixed it by accident
